export type Country = {
  name: string;
  code: string;
  dial: string;
  flag: string;
  /** Valid length range for the national (local) number, excluding the dial code. */
  length: [number, number];
};

export const countries: Country[] = [
  { name: "United States", code: "US", dial: "+1", flag: "🇺🇸", length: [10, 10] },
  { name: "Canada", code: "CA", dial: "+1", flag: "🇨🇦", length: [10, 10] },
  { name: "United Kingdom", code: "GB", dial: "+44", flag: "🇬🇧", length: [10, 10] },
  { name: "India", code: "IN", dial: "+91", flag: "🇮🇳", length: [10, 10] },
  { name: "Pakistan", code: "PK", dial: "+92", flag: "🇵🇰", length: [10, 10] },
  { name: "Indonesia", code: "ID", dial: "+62", flag: "🇮🇩", length: [9, 12] },
  { name: "Brazil", code: "BR", dial: "+55", flag: "🇧🇷", length: [10, 11] },
  { name: "Nigeria", code: "NG", dial: "+234", flag: "🇳🇬", length: [10, 10] },
  { name: "Bangladesh", code: "BD", dial: "+880", flag: "🇧🇩", length: [10, 10] },
  { name: "Russia", code: "RU", dial: "+7", flag: "🇷🇺", length: [10, 10] },
  { name: "Mexico", code: "MX", dial: "+52", flag: "🇲🇽", length: [10, 10] },
  { name: "Japan", code: "JP", dial: "+81", flag: "🇯🇵", length: [10, 10] },
  { name: "Germany", code: "DE", dial: "+49", flag: "🇩🇪", length: [10, 11] },
  { name: "France", code: "FR", dial: "+33", flag: "🇫🇷", length: [9, 9] },
  { name: "Italy", code: "IT", dial: "+39", flag: "🇮🇹", length: [9, 10] },
  { name: "Spain", code: "ES", dial: "+34", flag: "🇪🇸", length: [9, 9] },
  { name: "Australia", code: "AU", dial: "+61", flag: "🇦🇺", length: [9, 9] },
  { name: "South Africa", code: "ZA", dial: "+27", flag: "🇿🇦", length: [9, 9] },
  { name: "Saudi Arabia", code: "SA", dial: "+966", flag: "🇸🇦", length: [9, 9] },
  { name: "United Arab Emirates", code: "AE", dial: "+971", flag: "🇦🇪", length: [9, 9] },
  { name: "Egypt", code: "EG", dial: "+20", flag: "🇪🇬", length: [10, 10] },
  { name: "Turkey", code: "TR", dial: "+90", flag: "🇹🇷", length: [10, 10] },
  { name: "Vietnam", code: "VN", dial: "+84", flag: "🇻🇳", length: [9, 10] },
  { name: "Philippines", code: "PH", dial: "+63", flag: "🇵🇭", length: [10, 10] },
  { name: "Thailand", code: "TH", dial: "+66", flag: "🇹🇭", length: [9, 9] },
  { name: "Malaysia", code: "MY", dial: "+60", flag: "🇲🇾", length: [9, 10] },
  { name: "Singapore", code: "SG", dial: "+65", flag: "🇸🇬", length: [8, 8] },
  { name: "Netherlands", code: "NL", dial: "+31", flag: "🇳🇱", length: [9, 9] },
  { name: "Poland", code: "PL", dial: "+48", flag: "🇵🇱", length: [9, 9] },
  { name: "Ukraine", code: "UA", dial: "+380", flag: "🇺🇦", length: [9, 9] },
  { name: "Argentina", code: "AR", dial: "+54", flag: "🇦🇷", length: [10, 10] },
  { name: "Colombia", code: "CO", dial: "+57", flag: "🇨🇴", length: [10, 10] },
  { name: "Chile", code: "CL", dial: "+56", flag: "🇨🇱", length: [9, 9] },
  { name: "Peru", code: "PE", dial: "+51", flag: "🇵🇪", length: [9, 9] },
  { name: "Morocco", code: "MA", dial: "+212", flag: "🇲🇦", length: [9, 9] },
  { name: "Kenya", code: "KE", dial: "+254", flag: "🇰🇪", length: [9, 9] },
  { name: "Ghana", code: "GH", dial: "+233", flag: "🇬🇭", length: [9, 9] },
  { name: "Ethiopia", code: "ET", dial: "+251", flag: "🇪🇹", length: [9, 9] },
  { name: "Tanzania", code: "TZ", dial: "+255", flag: "🇹🇿", length: [9, 9] },
  { name: "Uganda", code: "UG", dial: "+256", flag: "🇺🇬", length: [9, 9] },
  { name: "Iraq", code: "IQ", dial: "+964", flag: "🇮🇶", length: [10, 10] },
  { name: "Iran", code: "IR", dial: "+98", flag: "🇮🇷", length: [10, 10] },
  { name: "Afghanistan", code: "AF", dial: "+93", flag: "🇦🇫", length: [9, 9] },
  { name: "Nepal", code: "NP", dial: "+977", flag: "🇳🇵", length: [10, 10] },
  { name: "Sri Lanka", code: "LK", dial: "+94", flag: "🇱🇰", length: [9, 9] },
  { name: "Myanmar", code: "MM", dial: "+95", flag: "🇲🇲", length: [9, 10] },
  { name: "Cambodia", code: "KH", dial: "+855", flag: "🇰🇭", length: [9, 9] },
  { name: "Kazakhstan", code: "KZ", dial: "+7", flag: "🇰🇿", length: [10, 10] },
  { name: "Uzbekistan", code: "UZ", dial: "+998", flag: "🇺🇿", length: [9, 9] },
  { name: "Azerbaijan", code: "AZ", dial: "+994", flag: "🇦🇿", length: [9, 9] },
  { name: "Georgia", code: "GE", dial: "+995", flag: "🇬🇪", length: [9, 9] },
  { name: "Greece", code: "GR", dial: "+30", flag: "🇬🇷", length: [10, 10] },
  { name: "Portugal", code: "PT", dial: "+351", flag: "🇵🇹", length: [9, 9] },
  { name: "Sweden", code: "SE", dial: "+46", flag: "🇸🇪", length: [9, 9] },
  { name: "Norway", code: "NO", dial: "+47", flag: "🇳🇴", length: [8, 8] },
  { name: "Denmark", code: "DK", dial: "+45", flag: "🇩🇰", length: [8, 8] },
  { name: "Finland", code: "FI", dial: "+358", flag: "🇫🇮", length: [9, 10] },
  { name: "Switzerland", code: "CH", dial: "+41", flag: "🇨🇭", length: [9, 9] },
  { name: "Austria", code: "AT", dial: "+43", flag: "🇦🇹", length: [10, 10] },
  { name: "Belgium", code: "BE", dial: "+32", flag: "🇧🇪", length: [9, 9] },
  { name: "Ireland", code: "IE", dial: "+353", flag: "🇮🇪", length: [9, 9] },
  { name: "Czech Republic", code: "CZ", dial: "+420", flag: "🇨🇿", length: [9, 9] },
  { name: "Romania", code: "RO", dial: "+40", flag: "🇷🇴", length: [9, 9] },
  { name: "Hungary", code: "HU", dial: "+36", flag: "🇭🇺", length: [9, 9] },
  { name: "Bulgaria", code: "BG", dial: "+359", flag: "🇧🇬", length: [9, 9] },
  { name: "Croatia", code: "HR", dial: "+385", flag: "🇭🇷", length: [9, 9] },
  { name: "Serbia", code: "RS", dial: "+381", flag: "🇷🇸", length: [9, 9] },
  { name: "Israel", code: "IL", dial: "+972", flag: "🇮🇱", length: [9, 9] },
  { name: "Jordan", code: "JO", dial: "+962", flag: "🇯🇴", length: [9, 9] },
  { name: "Lebanon", code: "LB", dial: "+961", flag: "🇱🇧", length: [8, 8] },
  { name: "Qatar", code: "QA", dial: "+974", flag: "🇶🇦", length: [8, 8] },
  { name: "Kuwait", code: "KW", dial: "+965", flag: "🇰🇼", length: [8, 8] },
  { name: "Bahrain", code: "BH", dial: "+973", flag: "🇧🇭", length: [8, 8] },
  { name: "Oman", code: "OM", dial: "+968", flag: "🇴🇲", length: [8, 8] },
  { name: "Yemen", code: "YE", dial: "+967", flag: "🇾🇪", length: [9, 9] },
  { name: "Tunisia", code: "TN", dial: "+216", flag: "🇹🇳", length: [8, 8] },
  { name: "Algeria", code: "DZ", dial: "+213", flag: "🇩🇿", length: [9, 9] },
  { name: "Libya", code: "LY", dial: "+218", flag: "🇱🇾", length: [9, 9] },
  { name: "Sudan", code: "SD", dial: "+249", flag: "🇸🇩", length: [9, 9] },
  { name: "Somalia", code: "SO", dial: "+252", flag: "🇸🇴", length: [8, 9] },
  { name: "Zimbabwe", code: "ZW", dial: "+263", flag: "🇿🇼", length: [9, 9] },
  { name: "Zambia", code: "ZM", dial: "+260", flag: "🇿🇲", length: [9, 9] },
  { name: "Mozambique", code: "MZ", dial: "+258", flag: "🇲🇿", length: [9, 9] },
  { name: "Angola", code: "AO", dial: "+244", flag: "🇦🇴", length: [9, 9] },
  { name: "Cameroon", code: "CM", dial: "+237", flag: "🇨🇲", length: [9, 9] },
  { name: "Ivory Coast", code: "CI", dial: "+225", flag: "🇨🇮", length: [8, 8] },
  { name: "Senegal", code: "SN", dial: "+221", flag: "🇸🇳", length: [9, 9] },
  { name: "Mali", code: "ML", dial: "+223", flag: "🇲🇱", length: [8, 8] },
  { name: "Niger", code: "NE", dial: "+227", flag: "🇳🇪", length: [8, 8] },
  { name: "Burkina Faso", code: "BF", dial: "+226", flag: "🇧🇫", length: [8, 8] },
  { name: "Guinea", code: "GN", dial: "+224", flag: "🇬🇳", length: [8, 8] },
  { name: "Rwanda", code: "RW", dial: "+250", flag: "🇷🇼", length: [9, 9] },
  { name: "Burundi", code: "BI", dial: "+257", flag: "🇧🇮", length: [8, 8] },
  { name: "Malawi", code: "MW", dial: "+265", flag: "🇲🇼", length: [9, 9] },
  { name: "Botswana", code: "BW", dial: "+267", flag: "🇧🇼", length: [8, 8] },
  { name: "Namibia", code: "NA", dial: "+264", flag: "🇳🇦", length: [9, 9] },
  { name: "Mauritius", code: "MU", dial: "+230", flag: "🇲🇺", length: [8, 8] },
  { name: "Madagascar", code: "MG", dial: "+261", flag: "🇲🇬", length: [9, 9] },
  { name: "New Zealand", code: "NZ", dial: "+64", flag: "🇳🇿", length: [9, 9] },
  { name: "Fiji", code: "FJ", dial: "+679", flag: "🇫🇯", length: [7, 7] },
  { name: "Papua New Guinea", code: "PG", dial: "+675", flag: "🇵🇬", length: [8, 8] },
  { name: "Cuba", code: "CU", dial: "+53", flag: "🇨🇺", length: [8, 8] },
  { name: "Dominican Republic", code: "DO", dial: "+1", flag: "🇩🇴", length: [10, 10] },
  { name: "Puerto Rico", code: "PR", dial: "+1", flag: "🇵🇷", length: [10, 10] },
  { name: "Guatemala", code: "GT", dial: "+502", flag: "🇬🇹", length: [8, 8] },
  { name: "Honduras", code: "HN", dial: "+504", flag: "🇭🇳", length: [8, 8] },
  { name: "El Salvador", code: "SV", dial: "+503", flag: "🇸🇻", length: [8, 8] },
  { name: "Nicaragua", code: "NI", dial: "+505", flag: "🇳🇮", length: [8, 8] },
  { name: "Costa Rica", code: "CR", dial: "+506", flag: "🇨🇷", length: [8, 8] },
  { name: "Panama", code: "PA", dial: "+507", flag: "🇵🇦", length: [8, 8] },
  { name: "Ecuador", code: "EC", dial: "+593", flag: "🇪🇨", length: [9, 9] },
  { name: "Venezuela", code: "VE", dial: "+58", flag: "🇻🇪", length: [10, 10] },
  { name: "Bolivia", code: "BO", dial: "+591", flag: "🇧🇴", length: [8, 8] },
  { name: "Paraguay", code: "PY", dial: "+595", flag: "🇵🇾", length: [9, 9] },
  { name: "Uruguay", code: "UY", dial: "+598", flag: "🇺🇾", length: [8, 8] },
  { name: "Jamaica", code: "JM", dial: "+1", flag: "🇯🇲", length: [10, 10] },
  { name: "Trinidad and Tobago", code: "TT", dial: "+1", flag: "🇹🇹", length: [10, 10] },
  { name: "Bahamas", code: "BS", dial: "+1", flag: "🇧🇸", length: [10, 10] },
  { name: "Barbados", code: "BB", dial: "+1", flag: "🇧🇧", length: [10, 10] },
  { name: "Guyana", code: "GY", dial: "+592", flag: "🇬🇾", length: [7, 7] },
  { name: "Suriname", code: "SR", dial: "+597", flag: "🇸🇷", length: [7, 7] },
  { name: "Belize", code: "BZ", dial: "+501", flag: "🇧🇿", length: [7, 7] },
  { name: "Haiti", code: "HT", dial: "+509", flag: "🇭🇹", length: [8, 8] },
  { name: "Iceland", code: "IS", dial: "+354", flag: "🇮🇸", length: [7, 7] },
  { name: "Luxembourg", code: "LU", dial: "+352", flag: "🇱🇺", length: [9, 9] },
  { name: "Malta", code: "MT", dial: "+356", flag: "🇲🇹", length: [8, 8] },
  { name: "Cyprus", code: "CY", dial: "+357", flag: "🇨🇾", length: [8, 8] },
  { name: "Estonia", code: "EE", dial: "+372", flag: "🇪🇪", length: [8, 8] },
  { name: "Latvia", code: "LV", dial: "+371", flag: "🇱🇻", length: [8, 8] },
  { name: "Lithuania", code: "LT", dial: "+370", flag: "🇱🇹", length: [8, 8] },
  { name: "Slovenia", code: "SI", dial: "+386", flag: "🇸🇮", length: [8, 8] },
  { name: "Slovakia", code: "SK", dial: "+421", flag: "🇸🇰", length: [9, 9] },
  { name: "North Macedonia", code: "MK", dial: "+389", flag: "🇲🇰", length: [8, 8] },
  { name: "Albania", code: "AL", dial: "+355", flag: "🇦🇱", length: [9, 9] },
  { name: "Bosnia and Herzegovina", code: "BA", dial: "+387", flag: "🇧🇦", length: [8, 8] },
  { name: "Moldova", code: "MD", dial: "+373", flag: "🇲🇩", length: [8, 8] },
  { name: "Belarus", code: "BY", dial: "+375", flag: "🇧🇾", length: [9, 9] },
  { name: "Armenia", code: "AM", dial: "+374", flag: "🇦🇲", length: [8, 8] },
  { name: "Tajikistan", code: "TJ", dial: "+992", flag: "🇹🇯", length: [9, 9] },
  { name: "Kyrgyzstan", code: "KG", dial: "+996", flag: "🇰🇬", length: [9, 9] },
  { name: "Turkmenistan", code: "TM", dial: "+993", flag: "🇹🇲", length: [8, 8] },
  { name: "Mauritania", code: "MR", dial: "+222", flag: "🇲🇷", length: [8, 8] },
  { name: "Chad", code: "TD", dial: "+235", flag: "🇹🇩", length: [8, 8] },
  { name: "Central African Republic", code: "CF", dial: "+236", flag: "🇨🇫", length: [8, 8] },
  { name: "Gabon", code: "GA", dial: "+241", flag: "🇬🇦", length: [8, 8] },
  { name: "Congo", code: "CG", dial: "+242", flag: "🇨🇬", length: [9, 9] },
  { name: "DR Congo", code: "CD", dial: "+243", flag: "🇨🇩", length: [9, 9] },
  { name: "Equatorial Guinea", code: "GQ", dial: "+240", flag: "🇬🇶", length: [9, 9] },
  { name: "Benin", code: "BJ", dial: "+229", flag: "🇧🇯", length: [8, 8] },
  { name: "Togo", code: "TG", dial: "+228", flag: "🇹🇬", length: [8, 8] },
  { name: "Sierra Leone", code: "SL", dial: "+232", flag: "🇸🇱", length: [8, 8] },
  { name: "Liberia", code: "LR", dial: "+231", flag: "🇱🇷", length: [8, 8] },
  { name: "Gambia", code: "GM", dial: "+220", flag: "🇬🇲", length: [7, 7] },
  { name: "Guinea-Bissau", code: "GW", dial: "+245", flag: "🇬🇼", length: [7, 7] },
  { name: "Cape Verde", code: "CV", dial: "+238", flag: "🇨🇻", length: [7, 7] },
  { name: "Sao Tome and Principe", code: "ST", dial: "+239", flag: "🇸🇹", length: [7, 7] },
  { name: "Comoros", code: "KM", dial: "+269", flag: "🇰🇲", length: [7, 7] },
  { name: "Seychelles", code: "SC", dial: "+248", flag: "🇸🇨", length: [7, 7] },
  { name: "Djibouti", code: "DJ", dial: "+253", flag: "🇩🇯", length: [8, 8] },
  { name: "Eritrea", code: "ER", dial: "+291", flag: "🇪🇷", length: [7, 7] },
  { name: "South Sudan", code: "SS", dial: "+211", flag: "🇸🇸", length: [9, 9] },
  { name: "Bhutan", code: "BT", dial: "+975", flag: "🇧🇹", length: [8, 8] },
  { name: "Maldives", code: "MV", dial: "+960", flag: "🇲🇻", length: [7, 7] },
  { name: "Brunei", code: "BN", dial: "+673", flag: "🇧🇳", length: [7, 7] },
  { name: "Timor-Leste", code: "TL", dial: "+670", flag: "🇹🇱", length: [8, 8] },
  { name: "Solomon Islands", code: "SB", dial: "+677", flag: "🇸🇧", length: [7, 7] },
  { name: "Vanuatu", code: "VU", dial: "+678", flag: "🇻🇺", length: [7, 7] },
  { name: "Samoa", code: "WS", dial: "+685", flag: "🇼🇸", length: [7, 7] },
  { name: "Tonga", code: "TO", dial: "+676", flag: "🇹🇴", length: [7, 7] },
  { name: "Kiribati", code: "KI", dial: "+686", flag: "🇰🇮", length: [8, 8] },
  { name: "Micronesia", code: "FM", dial: "+691", flag: "🇫🇲", length: [7, 7] },
  { name: "Marshall Islands", code: "MH", dial: "+692", flag: "🇲🇭", length: [7, 7] },
  { name: "Palau", code: "PW", dial: "+680", flag: "🇵🇼", length: [7, 7] },
  { name: "Nauru", code: "NR", dial: "+674", flag: "🇳🇷", length: [7, 7] },
  { name: "Tuvalu", code: "TV", dial: "+688", flag: "🇹🇻", length: [7, 7] },
  { name: "Andorra", code: "AD", dial: "+376", flag: "🇦🇩", length: [6, 6] },
  { name: "Monaco", code: "MC", dial: "+377", flag: "🇲🇨", length: [8, 8] },
  { name: "Liechtenstein", code: "LI", dial: "+423", flag: "🇱🇮", length: [7, 7] },
  { name: "San Marino", code: "SM", dial: "+378", flag: "🇸🇲", length: [9, 9] },
  { name: "Greenland", code: "GL", dial: "+299", flag: "🇬🇱", length: [6, 6] },
  { name: "Faroe Islands", code: "FO", dial: "+298", flag: "🇫🇴", length: [6, 6] },
  { name: "Gibraltar", code: "GI", dial: "+350", flag: "🇬🇮", length: [8, 8] },
  { name: "Bermuda", code: "BM", dial: "+1", flag: "🇧🇲", length: [10, 10] },
  { name: "Cayman Islands", code: "KY", dial: "+1", flag: "🇰🇾", length: [10, 10] },
  { name: "Aruba", code: "AW", dial: "+297", flag: "🇦🇼", length: [7, 7] },
  { name: "Curacao", code: "CW", dial: "+599", flag: "🇨🇼", length: [7, 7] },
  { name: "Hong Kong", code: "HK", dial: "+852", flag: "🇭🇰", length: [8, 8] },
  { name: "Macau", code: "MO", dial: "+853", flag: "🇲🇴", length: [8, 8] },
  { name: "Taiwan", code: "TW", dial: "+886", flag: "🇹🇼", length: [9, 9] },
  { name: "South Korea", code: "KR", dial: "+82", flag: "🇰🇷", length: [9, 10] },
  { name: "North Korea", code: "KP", dial: "+850", flag: "🇰🇵", length: [8, 9] },
  { name: "China", code: "CN", dial: "+86", flag: "🇨🇳", length: [11, 11] },
];

export type CheckResult = {
  valid: boolean;
  e164: string;
  national: string;
  country: Country;
  message: string;
};

/** Validate a national phone number against a country's expected length. */
export function validateNumber(input: string, country: Country): CheckResult {
  const raw = input.replace(/\D/g, "");
  const national = raw.replace(/^0+/, "");
  const length = national.length;
  const [min, max] = country.length;
  const valid = length >= min && length <= max;
  const e164 = `${country.dial}${national}`;

  return {
    valid,
    e164,
    national,
    country,
    message: valid
      ? `Valid ${country.name} number. Ready to check on WhatsApp.`
      : `Invalid ${country.name} number. Expected ${min}${
          max === min ? "" : `–${max}`
        } digits.`,
  };
}

/** Build a wa.me deep link that opens the number in WhatsApp. */
export function waLink(e164: string): string {
  return `https://wa.me/${e164.replace(/\D/g, "")}`;
}